// GENERATED by scripts/gen-sample.mjs — demo values. A real deployment
// replaces `publicKeys` + `fieldSchema` + `revocationList` with the firm's
// published key(s), the collection's attestation schema, and the latest signed
// revocation list. Re-run `node scripts/gen-sample.mjs` to refresh the demo.
// Re-running mints a NEW random keypair → replaces ALL bytes here and in
// public/sample-qr.txt; commit both files together to keep them in sync.
import type { VerifierConfig } from './verify-core.js'

export const config: VerifierConfig = {
  publicKeys: {
  "bd7e8268071ac41f": "hpbs5UQivCLgPolFRoj5h1Q12OCXFlZkZfff-mEiAPM"
},
  fieldSchema: {
  "fields": [
    {
      "path": "invoiceNo",
      "normalize": "alnum-upper"
    },
    {
      "path": "total",
      "normalize": "cents"
    },
    {
      "path": "issueDate",
      "normalize": "iso-date"
    }
  ]
},
  revocationList: {
  "v": 1,
  "revokedDocIds": [],
  "asOf": "2026-05-29T00:00:00.000Z",
  "keyId": "bd7e8268071ac41f",
  "sig": "JzGDN88XzGYB6Im0NC-XLUVAUEjQTHCqqyOhuoT72sFUeYgFJjYnT0N02bDRAeF5HchE-V-NxqwKf3R-4WzgDA"
},
}

/** Demo document a reader can load to see a green verdict without a real QR. */
export const sample: { qr: string; record: Record<string, unknown> } = {
  qr: "eyJ2IjoxLCJkb2NJZCI6IjAxSjAwMDAwMDAwMDAwMDAwMDAwMDBERU1PIiwic2FsdCI6ImZqRnpRUkVIZXVUX3Nvdy1MMkdrZ0EiLCJhbGciOiJlZDI1NTE5Iiwia2V5SWQiOiJiZDdlODI2ODA3MWFjNDFmIiwiZmllbGRIYXNoZXMiOlsiV3NSNU9sOW5rVUNwamJETm40N1o1bU1BYU0xeWNGaFRnMHFxaTg3Yjc4byIsIlBVT1FReWxzbUYyRzFtMDY5TDhvanNGdjhpUWRMdEpSdWVmN051VFNoNjQiLCJoQlV2RG84aUVGYzhIUER6ZG1Nb3hKRjE4bERPRDExcEtvcUF0aks2ZGNvIl0sInNpZyI6IjBnaFlRUF9iZDVPNnFEdGgzMy1YejA4UTdfSmJMOTZ6WDRIZlZQS0xZUDh0NHc2M01FVXNfNnpaSzE2ZEJ1V3dmRG9oM3k4bnBsckFTdE1aT0RKckRnIn0",
  record: {
  "invoiceNo": "INV-1042",
  "total": "1234.50",
  "issueDate": "2026-05-29"
},
}
