// Single source of truth for the hub's tsup entry map (#660).
//
// Shared by tsup.config.ts (the JS build — one invocation, all entries,
// `splitting: true` for cross-subpath class identity) and
// scripts/build.mjs (the single plain `tsc --emitDeclarationOnly` declaration
// pass — see that file for why it replaced tsup's rollup-dts bundling).
export const ENTRIES = {
  index: 'src/index.ts',
  'i18n/index': 'src/via/i18n/index.ts',
  'team/index': 'src/with-party/team/index.ts',
  'broker/index': 'src/with-party/broker/index.ts',
  'session/index': 'src/with-party/session/index.ts',
  'history/index': 'src/with-commit/history/index.ts',
  'forget/index': 'src/with-audit/forget/index.ts',
  'sealed-record/index': 'src/with-audit/sealed-record/index.ts',
  'query/index': 'src/kernel/query/index.ts',
  'blobs/index': 'src/via/blob/index.ts',
  'indexing/index': 'src/with-lookup/indexing/index.ts',
  'lazy/index': 'src/with-store/lazy/index.ts',
  'aggregate/index': 'src/with-lookup/aggregate/index.ts',
  'crdt/index': 'src/with-commit/crdt/index.ts',
  'pod/index': 'src/with-pod/index.ts',
  'consent/index': 'src/with-audit/consent/index.ts',
  'periods/index': 'src/with-audit/periods/index.ts',
  'guards/index': 'src/with-audit/guards/index.ts',
  'shadow/index': 'src/with-fork/shadow/index.ts',
  'snapshots/index': 'src/with-fork/snapshots/index.ts',
  'tx/index': 'src/with-commit/tx/index.ts',
  'derivations/index': 'src/with-formula/derivations/index.ts',
  'materialized-views/index': 'src/with-formula/materialized-views/index.ts',
  'overlay-views/index': 'src/with-formula/overlay-views/index.ts',
  'sync/index': 'src/with-party/sync/index.ts',
  'util/index': 'src/kernel/util/index.ts',
  'share-link/index': 'src/share-link/index.ts',
  'attestation/index': 'src/with-audit/attestation/index.ts',
  'classified/index': 'src/via/classified/index.ts',
  'satellites/index': 'src/with-shape/satellites/index.ts',
  'tiers/index': 'src/with-audit/tiers/index.ts',
  'portability/index': 'src/with-audit/portability/index.ts',
  'cargo/index': 'src/with-cargo/index.ts',
  'to/index': 'src/port/to/index.ts',
}
