import { writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  generateDocSigningKeyPair, computeFieldHashes, signPayloadCore, encodeQr,
  signRevocationList, bytesToB64url,
} from '@noy-db/attestation'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')

const fieldSchema = {
  fields: [
    { path: 'invoiceNo', normalize: 'alnum-upper' },
    { path: 'total', normalize: 'cents' },
    { path: 'issueDate', normalize: 'iso-date' },
  ],
}
const sampleRecord = { invoiceNo: 'INV-1042', total: '1234.50', issueDate: '2026-05-29' }
const docId = '01J0000000000000000000DEMO'

const k = await generateDocSigningKeyPair()
const salt = bytesToB64url(crypto.getRandomValues(new Uint8Array(16)))
const fieldHashes = await computeFieldHashes(salt, fieldSchema, sampleRecord)
const sig = await signPayloadCore({ v: 1, docId, salt, keyId: k.keyId, fieldHashes }, k.privateKeyPkcs8B64)
const qr = encodeQr({ v: 1, docId, salt, alg: 'ed25519', keyId: k.keyId, fieldHashes, sig })
const revocationList = await signRevocationList([], '2026-05-29T00:00:00.000Z', k.keyId, k.privateKeyPkcs8B64)

const configTs = `// GENERATED by scripts/gen-sample.mjs — demo values. A real deployment
// replaces \`publicKeys\` + \`fieldSchema\` + \`revocationList\` with the firm's
// published key(s), the collection's attestation schema, and the latest signed
// revocation list. Re-run \`node scripts/gen-sample.mjs\` to refresh the demo.
// Re-running mints a NEW random keypair → replaces ALL bytes here and in
// public/sample-qr.txt; commit both files together to keep them in sync.
import type { VerifierConfig } from './verify-core.js'

export const config: VerifierConfig = {
  publicKeys: ${JSON.stringify({ [k.keyId]: k.publicKeyB64 }, null, 2)},
  fieldSchema: ${JSON.stringify(fieldSchema, null, 2)},
  revocationList: ${JSON.stringify(revocationList, null, 2)},
}

/** Demo document a reader can load to see a green verdict without a real QR. */
export const sample: { qr: string; record: Record<string, unknown> } = {
  qr: ${JSON.stringify(qr)},
  record: ${JSON.stringify(sampleRecord, null, 2)},
}
`
writeFileSync(join(root, 'src/config.ts'), configTs)
mkdirSync(join(root, 'public'), { recursive: true })
writeFileSync(join(root, 'public/sample-qr.txt'), qr + '\n')
console.log('wrote src/config.ts + public/sample-qr.txt (keyId', k.keyId + ')')
